openapi: 3.0.0
info:
  title: basic_mongo_architecture
  version: 1.0.0
servers:
  - url: http://localhost:5600
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
paths:
  /api/v1/auth/login:
    post:
      tags:
        - General
      summary: Login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: user@yopmail.com
                device_id: '1234567789675'
                device_token: '3455788'
                device_type: os
                password: Vikas@123
      parameters:
        - name: Accept-Language
          in: header
          schema:
            type: string
          example: hn
        - name: x-api-key
          in: header
          schema:
            type: string
          example: >-
            kjghfhdfsshgndcljdjsflsdfljuy575itjkshkjoujoiuhjdjkjkjshskkjkjhsjkhjkhjkshkj
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/auth/send-otp:
    post:
      tags:
        - General
      summary: send-otp
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                phone_no: '987584849'
      parameters:
        - name: x-api-key
          in: header
          schema:
            type: string
          example: >-
            kjghfhdfsshgndcljdjsflsdfljuy575itjkshkjoujoiuhjdjkjkjshskkjkjhsjkhjkhjkshkj
        - name: Accept-Language
          in: header
          schema:
            type: string
          example: hn
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/auth/verify-otp:
    post:
      tags:
        - General
      summary: verify-otp
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                phone_no: ''
                otp: '998'
      parameters:
        - name: x-api-key
          in: header
          schema:
            type: string
          example: >-
            kjghfhdfsshgndcljdjsflsdfljuy575itjkshkjoujoiuhjdjkjkjshskkjkjhsjkhjkhjkshkj
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/auth/logout:
    post:
      tags:
        - General
      summary: Logout
      requestBody:
        content: {}
      security:
        - bearerAuth: []
      parameters:
        - name: x-api-key
          in: header
          schema:
            type: string
          example: >-
            kjghfhdfsshgndcljdjsflsdfljuy575itjkshkjoujoiuhjdjkjkjshskkjkjhsjkhjkhjkshkj
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}